table TSLA
	lineageTag: 5d379730-5a07-48d0-a5a6-69226e65c03a

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8f6f95cd-3087-4a27-92e5-381df9596e03
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 777ab599-b3f9-415f-bf5a-2ba716175e29
			defaultHierarchy: LocalDateTable_0cc02b6d-fdc9-447d-ad3a-305b1280228b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 66ad6aca-aa7f-4e63-b7d9-00ffa4051d56
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: ebd32e1c-c75f-4c9b-a0d0-fc439332df9c
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 8b43ac2c-13cd-400b-a3ae-df7faffe3466
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: 8b513ab1-a2cc-4b44-b707-da0895bd4069
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: 5ec80924-08ae-4538-9e0d-d8ef1ca019a0
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: 0833f703-9649-449d-83fd-6965c32a756c
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition TSLA = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\19788\Desktop\PBI Git\PBIBROTraining\TSLA.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

